# version isn't needed as of 2020 for docker compose CLI. 
# All 2.x and 3.x features supported
# version: '2'

# same as 
# docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site             
    ports:
      - '80:4000'


# volumes
  # .:/site ---------> dot before the colon means... mount the current working directory of docker host into site folder of docker container
  # 
# misc
  # its either volume (or) volumes
